name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs: # Job
  cd: # Job 이름

    runs-on: ubuntu-latest # Runner

    steps: # Step

      # ssh를 통해 EC2에 접속, 접속한 후에 실행할 스크립트 작성
      - name: Connect to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              cd Docker
              git pull
              sudo docker-compose down
              sudo docker-compose pull
              git submodule update --remote
              sudo docker-compose up -d --build
