name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: # Job
  cd: # Job 이름

    runs-on: ubuntu-latest 

    steps: # Step
    
      - name: Connect to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              cd Alddeul-Docker
              git pull
              sudo docker-compose -f "docker-compose.prod.yml" down
              sudo docker-compose -f "docker-compose.prod.yml" pull
              git submodule update --remote
              sudo docker-compose -f "docker-compose.prod.yml" up -d --build
