name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: file to Server
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.PRIVATE_KEY }}
         
         script: |
             cd Alddeul-Docker
             git pull
             sudo docker compose -p alddeul -f docker-compose.prod.yml down
             sudo docker compose -p alddeul -f docker-compose.prod.yml pull
             sudo docker compose -p alddeul -f docker-compose.prod.yml up -d --build
   
